server:
  port: 8080
  servlet:
    context-path: /datagrip/api

spring:
  profiles:
    include: datagrip
  main:
    allow-circular-references: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql:/localhost:5432/datagrip?rewriteBatchedStatements=true
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 60000
      connection-timeout: 60000
      validation-timeout: 5000
      read-only: false
      login-timeout: 5
  kafka:
    bootstrap-servers: localhost:9092

flink:
  cdc:
    schema-registry-url: http://localhost:8081
    database-username: cdcuser
    database-password: cdcpwd
